feat: added all links related to DSA course
kaiwalyakoparkar/classroom-monitor-bot pull request #60
Opened 2021-08-01 15:24 UTC by Ciggzy1312

Issue #53 has been fixed

Added all links related to the bootcamp :
   1. YouTube link of the Full course playlist
   2. Link to the repository for hands on practice of git
   3. Link to the repository of the whole syllabus and lectures cheatsheet

Command to check the links out : cm!dsa

2021-08-01 17:46 UTC, kaiwalyakoparkar requested changes
Please indent the code correctly :point_down: 
<img src="https://i.imgur.com/kzeUE59.png">

2021-08-01 18:29 UTC, Ciggzy1312 commented
It is showing that my code is indented properly

2021-08-02 03:25 UTC, kaiwalyakoparkar commented
@Ciggzy1312 I went to your repo. It still shows it's not indented. Look [here](https://github.com/Ciggzy1312/classroom-monitor-bot/blob/links/Commands/DSA.js#L19)

2021-08-02 04:01 UTC, Ciggzy1312 commented
Now check

2021-08-02 04:46 UTC, kaiwalyakoparkar requested changes

2021-08-02 04:46 UTC, kaiwalyakoparkar commented on Commands/DSA.js
> +	{
See this is not yet indented :sweat_smile:

2021-08-02 04:46 UTC, kaiwalyakoparkar commented on Commands/DSA.js
> +	},
This is not indented as well

2021-08-02 04:46 UTC, kaiwalyakoparkar commented on Commands/DSA.js
> +	}
This is not indented as well.

2021-08-02 04:54 UTC, Ciggzy1312 commented
![image](https://user-images.githubusercontent.com/65884232/127806017-256ca5b2-1edc-494e-a0c1-ab6a83dfd779.png)

It is showing indented in my repository :)

2021-08-02 05:05 UTC, kaiwalyakoparkar approved these changes
LGTM :rocket: Thanks for your collaboration and contribution

2021-08-02 05:05 UTC, merged